### ISSUE TITLE
Port is not refreshed when press on Back button

### ISSUE THREAD

**Issue by petitTrung** [drulabs/LocalDash#2]
Hello,

I pretty sure that the port is not refreshed when you quit application by pressing Back.

The next time when you re-open the application, the mPort value in AppController is not changed, that will cause some Socket problems further ....

**Comment by nabeelpkl** [comment]
I am also having the same problem. after successfully connecting for the first time and if swipe and close the app from recently used, next time its not able to connect. the device is not even showing after I advertise. It will work if I restart the phone. I am getting the following error in logcat.

```
05-30 15:49:00.951 21061-28049/com.vrdevotee.vendorapp W/System.err: java.net.ConnectException: Connection refused
05-30 15:49:00.954 21061-28049/com.vrdevotee.vendorapp W/System.err:     at java.net.PlainSocketImpl.socketConnect(Native Method)
05-30 15:49:00.955 21061-28049/com.vrdevotee.vendorapp W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
05-30 15:49:00.956 21061-28049/com.vrdevotee.vendorapp W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
05-30 15:49:00.957 21061-28049/com.vrdevotee.vendorapp W/System.err:     at java.net.Socket.connect(Socket.java:586)
        at java.net.Socket.connect(Socket.java:535)
        at java.net.Socket.<init>(Socket.java:427)
        at java.net.Socket.<init>(Socket.java:210)
        at com.vrdevotee.vendorapp.transfer.DataTransferService.onHandleIntent(DataTransferService.java:49)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
        at android.os.Handler.dispatchMessage(Handler.java:102)
05-30 15:49:00.958 21061-28049/com.vrdevotee.vendorapp W/System.err:     at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

any help is really appriciated.

**Comment by drulabs** [comment]
Hey guys, as you can see I haven't worked on the app for 2 years. If you find any solution, do raise a pull request.
